# Generated by Django 5.0.6 on 2024-07-19 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('author', models.CharField(max_length=300, verbose_name='author')),
                ('isbn', models.CharField(max_length=100, verbose_name='isbn')),
                ('description', models.CharField(max_length=3000, verbose_name='description')),
                ('language', models.CharField(max_length=50, verbose_name='language')),
                ('pages', models.PositiveIntegerField(verbose_name='pages')),
                ('likedPercent', models.IntegerField(verbose_name='likedPercent')),
                ('genere', models.ManyToManyField(related_name='books', to='Books.genere')),
            ],
        ),
    ]
