# Generated by Django 5.0.6 on 2024-07-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.CharField(max_length=5000, verbose_name="description"),
        ),
    ]
