# Generated by Django 5.0.6 on 2024-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(default='First edition', max_length=500, verbose_name='edition'),
        ),
    ]
