# Generated by Django 5.0.6 on 2024-07-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Books", "0003_book_edition"),
        ("users", "0002_userbookrating_usergenrepreference"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Genere",
            new_name="Genre",
        ),
    ]
