# Generated by Django 5.0.6 on 2024-07-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_rename_genere_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genere',
            new_name='genre',
        ),
    ]
