# Generated by Django 5.0.6 on 2024-08-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Books", "0005_rename_genere_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_image",
            field=models.ImageField(
                default="book_covers/default_cover.jpg",
                upload_to="book_covers/",
                verbose_name="Cover Image",
            ),
        ),
    ]
