# Generated by Django 5.0.6 on 2024-07-27 12:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="TvMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(max_length=40, verbose_name="Media type"),
                ),
                (
                    "original_title",
                    models.CharField(max_length=500, verbose_name="Original title"),
                ),
                (
                    "primary_title",
                    models.CharField(max_length=500, verbose_name="Primary title"),
                ),
                ("over18", models.BooleanField(verbose_name="Over 18")),
                ("startyear", models.IntegerField(verbose_name="Start year")),
                ("length", models.PositiveIntegerField(verbose_name="Length in mins")),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="tvmedia", to="moviesNshows.genre"
                    ),
                ),
            ],
        ),
    ]
