# Generated by Django 5.0.6 on 2024-07-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesNshows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvmedia',
            name='over18',
            field=models.BooleanField(default=False, verbose_name='Over 18'),
        ),
    ]
