# Generated by Django 5.0.6 on 2024-07-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesNshows', '0002_alter_tvmedia_over18'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvmedia',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Length in mins'),
        ),
        migrations.AlterField(
            model_name='tvmedia',
            name='primary_title',
            field=models.CharField(max_length=500, null=True, verbose_name='Primary title'),
        ),
        migrations.AlterField(
            model_name='tvmedia',
            name='startyear',
            field=models.DateField(null=True, verbose_name='Start year'),
        ),
    ]
